Use eza instead of exa
...since homebrew warned that exa is no longer supported:

```
Installing exa
Error: exa has been disabled because it is not maintained upstream! It was disabled on 2024-01-24.
Installing exa has failed!
```