Use doggo instead of dog
...since homebrew warned that dog is no longer supported:

```
Installing dog
Error: dog has been disabled because it is not maintained upstream! It was disabled on 2024-08-01.
Installing dog has failed!
```